Integrante 1 Diego Efraín Mojica \
Integrante 2 Esteban Umbarila \
integrante 3 Juan Ricardo Veloza García

#Análisis
En general el sharp ratio es negativo, lo que indica que la estrategia usada tiene mala predicción.

In [ ]:
import pandas as pd
import numpy as np
dataframe=pd.DataFrame()
dataframe["smd slow"]=[100,100,100,75,75,75,50,50,50]
dataframe["smd fast"]=[20,10,5,20,10,5,20,10,5]
dataframe["sharp ratio 6 meses"]=[0.388798,0.328482,0.188645,-0.603248,-0.480972,-0.368032,-0.302140,0.062375,0.013380]
dataframe["sharp ratio 2 años"]=[-0.823933,-0.928449,-0.933109,-1.227614,-1.087683,-1.036691,-1.228381,-1.004826,-0.991443]
dataframe["sharp ratio total"]=[0,0,0,0,0,0,0,0,0]
def promedio(x):
   return (x["sharp ratio 2 años"]+x["sharp ratio 6 meses"])/2

dataframe["sharp ratio total"] = dataframe.apply(promedio,axis=1)
dataframe.sort_values("sharp ratio total", ascending=False)

,smd slow,smd fast,sharp ratio 6 meses,sharp ratio 2 años,sharp ratio total
0,100,20,0.388798,-0.823933,-0.217568
1,100,10,0.328482,-0.928449,-0.299983
2,100,5,0.188645,-0.933109,-0.372232
7,50,10,0.062375,-1.004826,-0.471226
8,50,5,0.013380,-0.991443,-0.489032
5,75,5,-0.368032,-1.036691,-0.702362
6,50,20,-0.302140,-1.228381,-0.765261
4,75,10,-0.480972,-1.087683,-0.784327
3,75,20,-0.603248,-1.227614,-0.915431